#!/usr/bin/php
<?php
// - - - - - - - - - - - - - BEGIN LICENSE BLOCK - - - - - - - - - - - - -
// Version: MPL 1.1/GPL 2.0/LGPL 2.1
//
// The contents of this file are subject to the Mozilla Public License Version
// 1.1 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
// http://www.mozilla.org/MPL/
//
// Software distributed under the License is distributed on an "AS IS" basis,
// WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
// for the specific language governing rights and limitations under the
// License.
//
// The Original Code is sitefusion.sourceforge.net code.
//
// The Initial Developer of the Original Code is
// FrontDoor Media Group.
// Portions created by the Initial Developer are Copyright (C) 2009
// the Initial Developer. All Rights Reserved.
//
// Contributor(s):
//   Nikki Auburger <nikki@thefrontdoor.nl> (original author)
//   Tom Peeters <tom@thefrontdoor.nl>
//
// - - - - - - - - - - - - - - END LICENSE BLOCK - - - - - - - - - - - - -

function readline_c( $prompt = '' )
{
    echo $prompt;
    return rtrim( fgets( STDIN ), "\n" );
}

function ConsoleOutput($message)
{
    echo $message .PHP_EOL;
}

if (in_array('-c',$_SERVER['argv'])) {
	include_once "../conf/webfrontend.conf";

    $dbhost = $WEBCONFIG['databaseHost'];
    $dbuser = $WEBCONFIG['databaseUsername'];
    $dbpass = $WEBCONFIG['databasePassword'];
    $dbname = $WEBCONFIG['databaseName'];
}
else {
	$dbhost = readline_c( 'Database hostname (leave empty for 127.0.0.1): ' );
	$dbuser = readline_c( 'Database username: ' );
	$dbpass = readline_c( 'Database password: ' );
	$dbname = readline_c( 'Database name (leave empty for "sitefusion"): ' );
	$dbname = ($dbname == '' ? 'sitefusion':$dbname);
}

$dbhost = '' ? '127.0.0.1' : $dbhost;

$conn = new mysqli( $dbhost, $dbuser, $dbpass );

if ($conn->connect_error)
{
    die("Connection failed: " . $conn->connect_error . PHP_EOL );
}

$dbname_escaped = $conn->real_escape_string($dbname);

$sql = "CREATE DATABASE " . $dbname_escaped;

if ($conn->query($sql) === TRUE)
{
    ConsoleOutput("Database ' . $dbname . ' created successfully");
}
else
{
    ConsoleOutput("Database ' . $dbname . ' not created");
    
    ConsoleOutput("Check if already exists");    
    if($conn->select_db($dbname))
    {
        ConsoleOutput('OK, database ' . $dbname . ' succesfully selected!');
    }
    else
    {
        die("Cannot create or select database: " . $conn->error . PHP_EOL );
    }
}

$conn->select_db($dbname);

ConsoleOutput("Create table 'processes' if it doesn't exist...");

if( ! $conn->query( "CREATE TABLE IF NOT EXISTS `processes` (
	 `id` varchar(32) NOT NULL,
	 `type` varchar(10) NOT NULL,
	 `ident` varchar(32) NOT NULL,
	 `user` varchar(32) NOT NULL,
	 `app` varchar(64) NOT NULL,
	 `args` varchar(64) NOT NULL,
	 `client_ip` varchar(15) NOT NULL,
	 `port` int(11) NOT NULL,
	 `pid` int(11) NOT NULL,
	 `memory` bigint(20) NOT NULL,
	 `memory_peak` bigint(20) NOT NULL,
	 `nodes` int(11) NOT NULL,
	 PRIMARY KEY  (`id`)
	) ENGINE=MyISAM DEFAULT CHARSET=utf8;") )
	die( "Error: Could not create table: " . $conn->error . PHP_EOL );

ConsoleOutput("Create table 'jobs' if it doesn't exist...");

if( ! $conn->query( "CREATE TABLE IF NOT EXISTS `jobs` (
	  `id` int(11) NOT NULL auto_increment,
	  `owner` varchar(64) NOT NULL,
	  `job` varchar(64) NOT NULL,
	  `args` varchar(64) NOT NULL,
	  `minute` int(11) NOT NULL,
	  `hour` int(11) NOT NULL,
	  `monthday` int(11) NOT NULL,
	  `month` int(11) NOT NULL,
	  `weekday` int(11) NOT NULL,
	  `mail_output` varchar(64) NOT NULL,
	  PRIMARY KEY  (`id`)
	) ENGINE=MyISAM DEFAULT CHARSET=utf8;") )
	die( "Error: Could not create table: " . $conn->error . PHP_EOL );

ConsoleOutput("Create table 'services' if it doesn't exist...");

if( ! $conn->query( "CREATE TABLE IF NOT EXISTS `services` (
	  `id` int(11) NOT NULL auto_increment,
	  `owner` varchar(64) NOT NULL,
	  `service` varchar(64) NOT NULL,
	  `args` varchar(64) NOT NULL,
	  `daemon` tinyint(4) NOT NULL,
	  PRIMARY KEY  (`id`)
	) ENGINE=MyISAM DEFAULT CHARSET=utf8;") )
	die( "Error: Could not create table: " . $conn->error . PHP_EOL );

ConsoleOutput("All done!");
